maerlyn_twitter.homepage:
    path:     /
    defaults: { _controller: MaerlynTwitterBundle:Default:index }

maerlyn_twitter.tweet.mark_as_read:
    path:       /tweet/mark-as-read/{id}
    defaults:   { _controller: MaerlynTwitterBundle:Tweet:markAsRead }
