hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

google_login:
    pattern:  /login/check-google

maerlyn_twitter:
    resource: "@MaerlynTwitterBundle/Resources/config/routing.yml"
    prefix:   /
