security:
    providers:
        in_memory:
            memory: ~

        hwi:
            id: hwi_oauth.user.provider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            security: true
            anonymous: ~
            pattern: ^/
            oauth:
                resource_owners:
                    google: "/login/check-google"
                login_path: /login
                use_forward: false
                failure_path: /

                oauth_user_provider:
                    service: hwi_oauth.user.provider

    access_control:
        - { path: ^/(login|connect), role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(_(profiler|wdt)|css|images|js)/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, role: IS_AUTHENTICATED_FULLY }
